import Head from "next/head";
import axios from "axios";
import { useMutation, useQuery } from "@tanstack/react-query";

import type { Data as PlantsResponse } from "./api/getPlants";
import Plant from "~/components/Plant";

type TokenResponse = {
  token: string;
};

const login = () => axios.get<TokenResponse>("/api/login");
const getPlants = (token: string) =>
  axios.post<PlantsResponse>("/api/getPlants", {
    token,
  });

export default function Home() {
  const {
    refetch,
    isSuccess,
    data: tokenData,
  } = useQuery(["login"], {
    queryFn: login,
    enabled: false,
    onError(err) {
      console.log(err);
    },
  });

  const {
    mutate,
    isSuccess: isSuccess2,
    data: plantsData,
  } = useMutation(getPlants, {
    onError(err) {
      console.log(err);
    },
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='h-screen w-screen py-12'>
        <div className='container mx-auto flex w-full flex-col items-stretch gap-y-4'>
          <button
            className='cursor-pointer rounded-md bg-teal-600 py-2 px-4 text-center font-semibold text-white'
            onClick={() => refetch()}
          >
            login
          </button>
          {isSuccess && (
            <button
              className='cursor-pointer rounded-md bg-teal-600 py-2 px-4 text-center font-semibold text-white'
              onClick={() => mutate(tokenData.data.token)}
            >
              get all plants
            </button>
          )}
          {isSuccess2 && (
            <div className='my-6 space-y-6'>
              {plantsData.data.list.map((plant) => (
                <Plant
                  key={plant.plantCode}
                  {...plant}
                  token={tokenData?.data.token || ""}
                />
              ))}
            </div>
          )}
        </div>
      </main>
    </>
  );
}
